apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: go-apps
  name: go-apps
  namespace: mavenir-platform
spec:
  containers:
  - image: go-apps
    name: go-apps
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "sleep 9600"]