apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: gitea-repo4
  name: gitea-repo4
  namespace: mavenir-platform
spec:
  containers:
  - image: alpine
    name: gitea-repo
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "sleep 9600"]
    env:
      - name: SSH_KEY
        valueFrom:
          secretKeyRef:
            name: argo-ssh-secret
            key: ssh-publickey