apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: gitea-ssh
  name: gitea-ssh
  namespace: mavenir-platform
spec:
  containers:
  - image: tea-cli
    name: gitea-ssh
    imagePullPolicy: IfNotPresent
    command: 
     - sh
     - "-c"
     - |
       /bin/sh <<'EOF'
       PUB_KEY=$(echo $SSH_KEY|tr -d '\n')
       curl -v POST "http://gitea-http.mavenir-platform.svc.cluster.local:3000/api/v1/admin/users/mavenir-platform/keys" -H  "accept: application/json" -H  "Content-Type: application/json" -H "Authorization: Bearer 4564cc501058ed21169c8434da76c956776b605a" -d "{ \"key\": \"$PUB_KEY\",  \"read_only\": true,  \"title\": \"ujwala-test1-ssh\" }"
       EOF
    env:
      - name: SSH_KEY
        valueFrom:
          secretKeyRef:
            name: argo-ssh-secret
            key: ssh-publickey
