apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: gitea-tea
  name: gitea-tea
  namespace: mavenir-platform
spec:
  containers:
  - image: tea-cli
    name: gitea-tea
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "bash /scripts/tea-repo.sh" ]
    volumeMounts:
    - name: tea-vol 
      mountPath: /scripts
  volumes:
  - name: tea-vol
    configMap:
      name: test-script
      defaultMode: 0744