apiVersion: "v1"
kind: "Secret"
metadata:
  name: "token-secret"
  namespace: "{{ .Values.namespace }}"
data:
  password: {{ .Values.giteasecrets.password | b64enc }}
  username: {{ .Values.giteasecrets.username | b64enc }}